services:
  vane-community:
    image: vane-community:latest
    build:
      context: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - data:/home/vane-community/data
    restart: unless-stopped

volumes:
  data:
    name: 'vane-community-data'
