import { Clock, Edit, Share, Trash, FileText, FileDown } from 'lucide-react';
import { Message } from './ChatWindow';
import { useEffect, useState, Fragment } from 'react';
import { formatTimeDifference } from '@/lib/utils';
import DeleteChat from './DeleteChat';
import {
  Popover,
  PopoverButton,
  PopoverPanel,
  Transition,
} from '@headlessui/react';
import { useChat, Section } from '@/lib/hooks/useChat';
import { SourceBlock } from '@/lib/types';
import { useTranslation } from '@/lib/i18n';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import WaypointIcon from './Waypoints/WaypointIcon';
import {
  buildChatPrintDocumentHtml,
  executeIframePrint,
} from '@/lib/utils/printExport';

const downloadFile = (filename: string, content: string, type: string) => {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 0);
};

const exportTranslations: Record<
  string,
  {
    exportReport: string;
    defaultTitle: string;
    queriesCount: (n: number) => string;
    queryNum: (n: number) => string;
    vaneAnswer: string;
    sourcesTitle: (n: number) => string;
    model: string;
    time: string;
    tokens: string;
    generatedBy: string;
    user: string;
    assistant: string;
  }
> = {
  pl: {
    exportReport: 'Eksport raportu',
    defaultTitle: 'Raport z badania',
    queriesCount: (n) => `Liczba zapytań: ${n}`,
    queryNum: (n) => `Pytanie #${n}`,
    vaneAnswer: 'Odpowiedź Vane',
    sourcesTitle: (n) => `Źródła i Odnośniki (${n})`,
    model: 'Model',
    time: 'Czas',
    tokens: 'Tokeny',
    generatedBy: 'Wygenerowano przez Vane - Community',
    user: 'Użytkownik',
    assistant: 'Asystent',
  },
  en: {
    exportReport: 'Report Export',
    defaultTitle: 'Research Report',
    queriesCount: (n) => `Queries: ${n}`,
    queryNum: (n) => `Query #${n}`,
    vaneAnswer: 'Vane Answer',
    sourcesTitle: (n) => `Sources & References (${n})`,
    model: 'Model',
    time: 'Time',
    tokens: 'Tokens',
    generatedBy: 'Generated by Vane - Community',
    user: 'User',
    assistant: 'Assistant',
  },
  de: {
    exportReport: 'Berichtsexport',
    defaultTitle: 'Recherchebericht',
    queriesCount: (n) => `Anzahl der Anfragen: ${n}`,
    queryNum: (n) => `Frage #${n}`,
    vaneAnswer: 'Vane Antwort',
    sourcesTitle: (n) => `Quellen & Referenzen (${n})`,
    model: 'Modell',
    time: 'Zeit',
    tokens: 'Tokens',
    generatedBy: 'Generiert von Vane - Community',
    user: 'Benutzer',
    assistant: 'Assistent',
  },
  es: {
    exportReport: 'Exportación de informe',
    defaultTitle: 'Informe de investigación',
    queriesCount: (n) => `Consultas: ${n}`,
    queryNum: (n) => `Pregunta #${n}`,
    vaneAnswer: 'Respuesta de Vane',
    sourcesTitle: (n) => `Fuentes y referencias (${n})`,
    model: 'Modelo',
    time: 'Tiempo',
    tokens: 'Tokens',
    generatedBy: 'Generado por Vane - Community',
    user: 'Usuario',
    assistant: 'Asistente',
  },
  fr: {
    exportReport: 'Exportation du rapport',
    defaultTitle: 'Rapport de recherche',
    queriesCount: (n) => `Requêtes: ${n}`,
    queryNum: (n) => `Question #${n}`,
    vaneAnswer: 'Réponse Vane',
    sourcesTitle: (n) => `Sources & Références (${n})`,
    model: 'Modèle',
    time: 'Temps',
    tokens: 'Jetons',
    generatedBy: 'Généré par Vane - Community',
    user: 'Utilisateur',
    assistant: 'Assistant',
  },
  it: {
    exportReport: 'Esportazione del report',
    defaultTitle: 'Report di ricerca',
    queriesCount: (n) => `Query: ${n}`,
    queryNum: (n) => `Domanda #${n}`,
    vaneAnswer: 'Risposta Vane',
    sourcesTitle: (n) => `Fonti e riferimenti (${n})`,
    model: 'Modello',
    time: 'Tempo',
    tokens: 'Token',
    generatedBy: 'Generato da Vane - Community',
    user: 'Utente',
    assistant: 'Assistente',
  },
  ja: {
    exportReport: 'レポートのエクスポート',
    defaultTitle: 'リサーチレポート',
    queriesCount: (n) => `クエリ数: ${n}`,
    queryNum: (n) => `質問 #${n}`,
    vaneAnswer: 'Vaneの回答',
    sourcesTitle: (n) => `情報源と参照 (${n})`,
    model: 'モデル',
    time: '時間',
    tokens: 'トークン',
    generatedBy: 'Vane - Community によって生成されました',
    user: 'ユーザー',
    assistant: 'アシスタント',
  },
  zh: {
    exportReport: '导出报告',
    defaultTitle: '研究报告',
    queriesCount: (n) => `查询次数: ${n}`,
    queryNum: (n) => `问题 #${n}`,
    vaneAnswer: 'Vane 回答',
    sourcesTitle: (n) => `来源与参考 (${n})`,
    model: '模型',
    time: '耗时',
    tokens: 'Token',
    generatedBy: '由 Vane - Community 生成',
    user: '用户',
    assistant: '助手',
  },
  ru: {
    exportReport: 'Экспорт отчета',
    defaultTitle: 'Отчет об исследовании',
    queriesCount: (n) => `Запросов: ${n}`,
    queryNum: (n) => `Вопрос #${n}`,
    vaneAnswer: 'Ответ Vane',
    sourcesTitle: (n) => `Источники и ссылки (${n})`,
    model: 'Модель',
    time: 'Время',
    tokens: 'Токены',
    generatedBy: 'Создано в Vane - Community',
    user: 'Пользователь',
    assistant: 'Ассистент',
  },
  uk: {
    exportReport: 'Експорт звіту',
    defaultTitle: 'Звіт про дослідження',
    queriesCount: (n) => `Запитів: ${n}`,
    queryNum: (n) => `Питання #${n}`,
    vaneAnswer: 'Відповідь Vane',
    sourcesTitle: (n) => `Джерела та посилання (${n})`,
    model: 'Модель',
    time: 'Час',
    tokens: 'Токени',
    generatedBy: 'Згенеровано Vane - Community',
    user: 'Користувач',
    assistant: 'Асистент',
  },
  pt: {
    exportReport: 'Exportação de relatório',
    defaultTitle: 'Relatório de pesquisa',
    queriesCount: (n) => `Consultas: ${n}`,
    queryNum: (n) => `Pergunta #${n}`,
    vaneAnswer: 'Resposta Vane',
    sourcesTitle: (n) => `Fontes e referências (${n})`,
    model: 'Modelo',
    time: 'Tempo',
    tokens: 'Tokens',
    generatedBy: 'Gerado por Vane - Community',
    user: 'Usuário',
    assistant: 'Assistente',
  },
  ko: {
    exportReport: '보고서 내보내기',
    defaultTitle: '조사 보고서',
    queriesCount: (n) => `질문 수: ${n}`,
    queryNum: (n) => `질문 #${n}`,
    vaneAnswer: 'Vane 답변',
    sourcesTitle: (n) => `출처 및 참고문헌 (${n})`,
    model: '모델',
    time: '소요 시간',
    tokens: '토큰',
    generatedBy: 'Vane - Community에서 생성됨',
    user: '사용자',
    assistant: '어시스턴트',
  },
};

const getExportLocale = (locale?: string) => {
  if (!locale) return exportTranslations.en;
  return exportTranslations[locale] || exportTranslations.en;
};

const exportAsMarkdown = (
  sections: Section[],
  title: string,
  locale: string = 'en',
) => {
  const tr = getExportLocale(locale);
  const date = new Date(
    sections[0]?.message?.createdAt || Date.now(),
  ).toLocaleString(locale || undefined);
  let md = `# 💬 ${tr.exportReport}: ${title || tr.defaultTitle}\n\n`;
  md += `*${tr.generatedBy} • ${date}*\n\n---\n`;

  sections.forEach((section, idx) => {
    md += `\n---\n`;
    md += `**🧑 ${tr.user}**  \n`;
    md += `*${new Date(section.message.createdAt).toLocaleString(locale || undefined)}*\n\n`;
    md += `> ${section.message.query.replace(/\n/g, '\n> ')}\n`;

    if (section.message.responseBlocks.length > 0) {
      let rawText = section.parsedTextBlocks.join('\n\n');
      // Clean think tags
      rawText = rawText.replace(/<think>[\s\S]*?<\/think>/g, '').trim();
      // Clean citation tags with arbitrary attributes to [NUM](URL) or [NUM]
      rawText = rawText.replace(
        /<citation\b([^>]*)>([\s\S]*?)<\/citation>/gi,
        (_, rawAttrs, content) => {
          const num = content.trim();
          const hrefMatch = rawAttrs.match(/href="([^"]*)"/i);
          const href = hrefMatch ? hrefMatch[1].trim() : '';
          return href && href.startsWith('http')
            ? `[${num}](${href})`
            : `[${num}]`;
        },
      );

      md += `\n---\n`;
      md += `**🤖 ${tr.assistant}**  \n`;
      md += `*${new Date(section.message.createdAt).toLocaleString(locale || undefined)}*\n\n`;
      md += `> ${rawText.replace(/\n/g, '\n> ')}\n`;
    }

    const sourceResponseBlock = section.message.responseBlocks.find(
      (block) => block.type === 'source',
    ) as SourceBlock | undefined;

    if (
      sourceResponseBlock &&
      sourceResponseBlock.data &&
      sourceResponseBlock.data.length > 0
    ) {
      md += `\n**${tr.sourcesTitle(sourceResponseBlock.data.length)}:**\n`;
      sourceResponseBlock.data.forEach((src: any, i: number) => {
        const url = src.metadata?.url || '';
        const name = src.metadata?.title || url;
        md += `- [${i + 1}] [${name}](${url})\n`;
      });
    }
  });
  md += '\n---\n';
  downloadFile(`${title || 'chat'}.md`, md, 'text/markdown');
};

const exportAsPDF = async (
  sections: Section[],
  title: string,
  locale: string = 'en',
) => {
  const tr = getExportLocale(locale);

  const turns = sections.map((section) => {
    const sourceResponseBlock = section.message.responseBlocks.find(
      (block) => block.type === 'source',
    ) as SourceBlock | undefined;

    return {
      userQuery: section.message.query,
      userDate: new Date(section.message.createdAt).toLocaleString(
        locale || undefined,
      ),
      assistantText: section.parsedTextBlocks.join('\n\n'),
      assistantDate: new Date(section.message.createdAt).toLocaleString(
        locale || undefined,
      ),
      sources: sourceResponseBlock?.data || [],
      metrics: section.metrics,
    };
  });

  const html = await buildChatPrintDocumentHtml({
    title: title || tr.defaultTitle,
    locale,
    turns,
    labels: {
      exportReport: tr.exportReport,
      user: tr.user,
      assistant: tr.assistant,
      sourcesTitle: tr.sourcesTitle,
      generatedBy: tr.generatedBy,
      queriesCount: tr.queriesCount,
      queryNum: tr.queryNum,
      model: tr.model,
      time: tr.time,
      tokens: tr.tokens,
      vaneAnswer: tr.vaneAnswer,
    },
  });

  executeIframePrint(html);
};

const Navbar = () => {
  const [title, setTitle] = useState<string>('');
  const [timeAgo, setTimeAgo] = useState<string>('');

  const { sections, chatId, resetChat, waypointId, waypointInfo } = useChat();
  const { t, locale } = useTranslation();
  const router = useRouter();

  useEffect(() => {
    if (sections.length > 0 && sections[0].message) {
      const newTitle =
        sections[0].message.query.length > 30
          ? `${sections[0].message.query.substring(0, 30).trim()}...`
          : sections[0].message.query || t('chat.newConversation');

      setTitle(newTitle);
      const newTimeAgo = formatTimeDifference(
        new Date(),
        sections[0].message.createdAt,
        locale,
      );
      setTimeAgo(newTimeAgo);
    }
  }, [sections, locale, t]);

  useEffect(() => {
    const intervalId = setInterval(() => {
      if (sections.length > 0 && sections[0].message) {
        const newTimeAgo = formatTimeDifference(
          new Date(),
          sections[0].message.createdAt,
          locale,
        );
        setTimeAgo(newTimeAgo);
      }
    }, 1000);

    return () => clearInterval(intervalId);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sections, locale]);

  return (
    <div className="sticky -mx-4 lg:mx-0 top-0 z-40 bg-light-primary/95 dark:bg-dark-primary/95 backdrop-blur-sm border-b border-light-200/50 dark:border-dark-200/30">
      <div className="px-4 lg:px-6 py-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center min-w-0">
            <button
              type="button"
              onClick={() => {
                resetChat();
                router.push('/');
              }}
              title={
                t('navigation.newQuery') ||
                t('chat.startNewChat') ||
                'New query'
              }
              className="lg:hidden mr-3 p-2 -ml-2 rounded-lg hover:bg-light-secondary dark:hover:bg-dark-secondary transition-colors duration-200"
            >
              <Edit size={18} className="text-black/70 dark:text-white/70" />
            </button>
            <div className="hidden lg:flex items-center gap-2 text-black/50 dark:text-white/50 min-w-0">
              <Clock size={14} />
              <span className="text-xs whitespace-nowrap">{timeAgo}</span>
            </div>
          </div>

          <div className="flex-1 mx-4 min-w-0 flex flex-col items-center">
            {waypointId && (
              <Link
                href={`/waypoints/${waypointId}`}
                title={t('waypoints.backToWaypoints') || 'Back to waypoints'}
                className="inline-flex items-center gap-1.5 text-[10px] font-semibold text-[#b8864d] hover:brightness-125 transition mb-0.5 bg-[#b8864d]/10 border border-[#b8864d]/30 px-2.5 py-0.5 rounded-full"
              >
                <WaypointIcon name={waypointInfo?.icon || 'Waypoints'} size={11} />
                <span className="truncate max-w-[180px]">{waypointInfo?.name || 'Waypoint'}</span>
              </Link>
            )}
            <h1 className="text-center text-sm font-medium text-black/80 dark:text-white/90 truncate max-w-full">
              {title || t('chat.newConversation')}
            </h1>
          </div>

          <div className="flex items-center gap-1 min-w-0">
            <Popover className="relative">
              <PopoverButton className="p-2 rounded-lg hover:bg-light-secondary dark:hover:bg-dark-secondary transition-colors duration-200">
                <Share size={16} className="text-black/60 dark:text-white/60" />
              </PopoverButton>
              <Transition
                as={Fragment}
                enter="transition ease-out duration-200"
                enterFrom="opacity-0 translate-y-1"
                enterTo="opacity-100 translate-y-0"
                leave="transition ease-in duration-150"
                leaveFrom="opacity-100 translate-y-0"
                leaveTo="opacity-0 translate-y-1"
              >
                <PopoverPanel className="absolute right-0 mt-2 w-64 origin-top-right rounded-2xl bg-light-primary dark:bg-[#161412] border border-light-200 dark:border-[#28221b] shadow-xl shadow-black/10 dark:shadow-black/40 z-50">
                  <div className="p-3">
                    <div className="mb-2 px-1">
                      <p className="text-xs font-semibold text-black/50 dark:text-[#b8864d] uppercase tracking-wide">
                        {t('chat.exportChat')}
                      </p>
                    </div>
                    <div className="space-y-1">
                      <button
                        className="w-full flex items-center gap-3 px-3 py-2 text-left rounded-xl hover:bg-light-secondary dark:hover:bg-[#201b16] transition-colors duration-200"
                        onClick={() =>
                          exportAsMarkdown(sections, title || '', locale)
                        }
                      >
                        <FileText size={16} className="text-[#b8864d]" />
                        <div>
                          <p className="text-sm font-medium text-black dark:text-stone-200">
                            Markdown
                          </p>
                          <p className="text-xs text-black/50 dark:text-stone-400">
                            .md format
                          </p>
                        </div>
                      </button>
                      <button
                        className="w-full flex items-center gap-3 px-3 py-2 text-left rounded-xl hover:bg-light-secondary dark:hover:bg-[#201b16] transition-colors duration-200"
                        onClick={() =>
                          exportAsPDF(sections, title || '', locale)
                        }
                      >
                        <FileDown size={16} className="text-[#b8864d]" />
                        <div>
                          <p className="text-sm font-medium text-black dark:text-stone-200">
                            PDF
                          </p>
                          <p className="text-xs text-black/50 dark:text-stone-400">
                            Document format
                          </p>
                        </div>
                      </button>
                    </div>
                  </div>
                </PopoverPanel>
              </Transition>
            </Popover>
            <DeleteChat
              redirect
              chatId={chatId!}
              chats={[]}
              setChats={() => {}}
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Navbar;
